// Generated by CoffeeScript 1.10.0
// Verifies that the CoffeeScript compiler runs.
(function () {
  // console.log writes to STDOUT
  console.log("Hello from CoffeeScript!");
}).call(this);

// Run with: node test.js
